version: '3.9'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db
    networks:
      - resultapp

  appservice:
    build: .
    restart: always
    ports:
      - 5000:5000
    environment:
      HOSTNAME: appservice
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: service-registry
      PORT: 5000
      DB_URI: mongodb://mongo_db:27017
    depends_on:
      - mongo_db
    networks:
      - resultapp
    
  service-registry:
    image: steeltoeoss/eureka-server
    ports:
      - 8761:8761
    networks:
      - resultapp

volumes:
  mongo_db: {}

networks:
  resultapp: